name: Design Pattern Tutorial - Test integration

variables:
  enviromentTest: DesignPatternTutorial
  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: 
        dotnet test ${enviromentTest}Test/ --no-build --verbosity normal
