name: Design Pattern Tutorial - Test integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: dotnet test --no-build --verbosity normal
